name: Sync to Proxmox

# Build on push to the main branch
on:
  push:
    branches: [ main ]

jobs:
# Make sure the job runs on the self-hosted runner
  build-test-store:
    runs-on: self-hosted
    steps:
    - name: Check out the respository
      uses: actions/checkout@main
    - name: Install Dependencies
      run: |
        sudo apt update && apt install -y make
    - name: Build
      run: make build
    - name: Store artifacts
      uses: actions/upload-artifact@main
      with:
        name: status-pva-${{ github.sha }}
        path: ./build
